Reset infectedStatus when scanning new item
nextcloud/files_antivirus pull request #169
Opened 2020-09-23 20:09 UTC by bpatath

Fix #167 by resetting the `infectedStatus` property of the scanner when starting to scan a new file.

I went ahead and implemented solution two, since it is actually much easier than I thought.
Just reset the `infectedStatus` when using the `scan` method since it is used by and only by the background scanner, and once per file (versus multiple times per file for the `initScanner` function).

2020-10-05 19:11 UTC, bpatath commented
@rullzer I see that you are the maintainer. I don't know what the typical Nextcloud timings are, but you may want to merge this quickly, and do a minor release. For users who chose the "delete" action for infected files during background scan, there is a risk that a huge part (potentially all) of the files stored on NC are deleted.

2020-11-25 11:12 UTC, xkill approved these changes
Fix works fine

2020-12-06 13:24 UTC, xkill requested changes
Hi, the code seems OK, but I tried it and, even if the status is reset, the next file scanned is also marked infected after finding a virus on a file.

Ex:

File id: 1111 -> Virus Found XXXXX (infected)
File id: 1112 -> Virus Found XXXXX (but it is not infected).

The following screenshot show few samples I found on my server logs. Not always mark the next file as infected, but 99%.

![https://cloud.locolandia.net/s/5k3N8CZTKoHGYWd/preview](https://cloud.locolandia.net/s/5k3N8CZTKoHGYWd/preview)

2020-12-10 13:59 UTC, rullzer approved these changes
Thanks!

2020-12-10 13:59 UTC, merged

2020-12-10 14:00 UTC, rullzer commented
> @rullzer I see that you are the maintainer. I don't know what the typical Nextcloud timings are, but you may want to merge this quickly, and do a minor release. For users who chose the "delete" action for infected files during background scan, there is a risk that a huge part (potentially all) of the files stored on NC are deleted.

Thanks. Sorry this got drowned in my github notifications while I was on holiday back then