Migrate away from deprecated interfaces and cleanup typing
nextcloud/files_antivirus pull request #247
Opened 2022-09-29 14:59 UTC by come-nc

Signed-off-by: Côme Chilliet <come.chilliet@nextcloud.com>

2022-09-29 20:03 UTC, come-nc commented
Should be good now, EOL version would need to be removed from expected, and maybe in info.xml we should put 23 as minimum?

2022-09-30 11:07 UTC, blizzz requested changes
v

2022-09-30 11:07 UTC, blizzz commented on lib/BackgroundJob/BackgroundScanner.php
> +	protected IRootFolder $rootFolder;
property types are available in PHP 7.4 only, but NC 23 supports 7.3

2022-09-30 12:15 UTC, come-nc commented on lib/BackgroundJob/BackgroundScanner.php
> +	protected IRootFolder $rootFolder;
Hum, still now?
7.3 has been EOL for a year.

2022-09-30 12:44 UTC, blizzz commented on lib/BackgroundJob/BackgroundScanner.php
> +	protected IRootFolder $rootFolder;
does not make anyone stop using it… we never withdraw support of a PHP version in an existing release

2022-09-30 13:17 UTC, come-nc commented on lib/BackgroundJob/BackgroundScanner.php
> +	protected IRootFolder $rootFolder;
Can I branch out stable23 then?

2022-09-30 15:06 UTC, blizzz commented on lib/BackgroundJob/BackgroundScanner.php
> +	protected IRootFolder $rootFolder;
sure

2022-10-01 11:50 UTC, come-nc commented on lib/BackgroundJob/BackgroundScanner.php
> +	protected IRootFolder $rootFolder;
I created stable23 branch, and bumped this one to 24 minimum and 4.0.0 version number (according to our documentation dropping a Nextcloud version is major version bump material, hope I understood that correctly).

Did I do things right?

2022-10-01 13:20 UTC, icewind1991 approved these changes
:rocket:

2022-10-01 13:37 UTC, come-nc commented on lib/BackgroundJob/BackgroundScanner.php
> +	protected IRootFolder $rootFolder;
Nope, I messed up, there is a `stable3.3` that is already good for 23, so I’m deleting the stable23 branch I did, and only the major bump and minimum version bump on master should be enough.

2022-10-01 13:58 UTC, blizzz commented on .github/workflows/lint.yml
> +        ocp-version: ['^v23.0.0', 'dev-master']
```suggestion
        ocp-version: ['^v24.0.0', 'dev-master']
```

2022-10-01 13:59 UTC, blizzz commented on .github/workflows/phpunit.yml
> +        server-versions: ['stable23', 'stable24', 'master']
```suggestion
        server-versions: ['stable24', 'stable25', 'master']
```

2022-10-01 13:59 UTC, blizzz commented on .github/workflows/static-analysis.yml
> +              ocp-version: ['dev-stable23', 'dev-stable24', 'dev-stable25', 'dev-master' ]
```suggestion
              ocp-version: ['dev-stable24', 'dev-stable25', 'dev-master' ]
```

2022-10-01 14:00 UTC, blizzz commented on composer.json
> +		"christophwurst/nextcloud": "^v23.0.0",
```suggestion
		"christophwurst/nextcloud": "^v24.0.0",
```

2022-10-01 14:02 UTC, blizzz commented on lib/BackgroundJob/BackgroundScanner.php
> +			$this->logger->error($e->getMessage(), ['exception' => $e]);
does it add the app option automatically now? if not – everywhere else we add it iirc –  providing this would also be good. But no regression to old code.

2022-10-01 14:05 UTC, blizzz approved these changes
apart of minor comments on the supported version dumps

2022-10-01 15:40 UTC, come-nc commented on lib/BackgroundJob/BackgroundScanner.php
> +			$this->logger->error($e->getMessage(), ['exception' => $e]);
From what I understood when using DI the app is automatically set, but I did not actually check it works…

2022-10-01 15:56 UTC, come-nc commented
@blizzz @icewind1991 Can one of you remove php7.4-sqlite-stable20 , php7.4-sqlite-stable21 and php7.4-sqlite-stable22 from expected CI?

2022-10-01 17:20 UTC, merged

2022-10-01 17:21 UTC, blizzz commented
> @blizzz @icewind1991 Can one of you remove php7.4-sqlite-stable20 , php7.4-sqlite-stable21 and php7.4-sqlite-stable22 from expected CI?

done.