chore(CI): Update master php testing versions and workflow templates
nextcloud/files_antivirus pull request #264
Opened 2023-01-16 15:21 UTC by nickvergessen

Signed-off-by: Joas Schilling <coding@schilljs.com>

2023-01-16 16:35 UTC, come-nc requested changes
There is https://github.com/nextcloud/files_antivirus/blob/master/.github/workflows/static-analysis.yml , should it be deleted in favor of psalm-matrix.yml?

2023-01-26 08:24 UTC, juliushaertl approved these changes

2023-01-26 09:34 UTC, come-nc approved these changes

2023-01-26 09:34 UTC, come-nc commented
Expected ci needs to be adapted by an admin

2023-01-26 16:18 UTC, juliushaertl commented
Will do so after merge as only then the jobs show up there.

2023-01-26 16:19 UTC, merged